// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZQN1rcYENe6DJ0tTeT1yDkxdpbz3kGIk',
    appId: '1:76986820994:web:862a1f193d27d08548079b',
    messagingSenderId: '76986820994',
    projectId: 'ingresafe-2248a',
    authDomain: 'ingresafe-2248a.firebaseapp.com',
    storageBucket: 'ingresafe-2248a.firebasestorage.app',
    measurementId: 'G-PFYHZ2WLT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCn68zNnA_Dku38bgd2WKdZmwRbEYWgjM',
    appId: '1:76986820994:android:bbf29ef4556e502f48079b',
    messagingSenderId: '76986820994',
    projectId: 'ingresafe-2248a',
    storageBucket: 'ingresafe-2248a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fXTgvJP_fnabCHUQ6XvT3Kz7n6hGHrY',
    appId: '1:76986820994:ios:8c4b5e3ea356000348079b',
    messagingSenderId: '76986820994',
    projectId: 'ingresafe-2248a',
    storageBucket: 'ingresafe-2248a.firebasestorage.app',
    iosBundleId: 'com.example.ingresafe',
  );
}
